name = "shart-platform-prod"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]

routes = [
  { pattern = "shart.cloud/*", zone_name = "shart.cloud" },
  { pattern = "www.shart.cloud/*", zone_name = "shart.cloud" }
]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
